# prevents inserting a blank line between shell prompts
add_newline = false

# Disables the line_break module, make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
success_symbol = "[-> ](bold green)"
error_symbol = "[-> ](bold red)"


[package]
symbol = "ï£– "
format = "[$symbol$version](bold blue) "

[java]
symbol = "î‰– "
format = "[$symbol$version](bold red) "

[lua]
symbol = "ğŸŒ• "
format = "via [$symbol$version](bold blue) "

[perl]
symbol = "î© "
format = "[$symbol$version](bold yellow) "

[php]
symbol = "ğŸ”¹ "
format = "[$symbol$version](bold yelllow) "

[python]
symbol = "î˜† "
format = "[$symbol$version](bold green) "

[ruby]
symbol = "îˆ¾ "
format = "[$symbol$version](bold red) "

[rust]
symbol = "î¨ "
format = "[$symbol$version](bold orange) "

